[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "aoc2015_01"
path = "src/aoc2015_01.rs"

[[bin]]
name = "aoc2015_02"
path = "src/aoc2015_02.rs"

[[bin]]
name = "aoc2015_03"
path = "src/aoc2015_03.rs"

[[bin]]
name = "aoc2015_04"
path = "src/aoc2015_04.rs"

[[bin]]
name = "aoc2015_05"
path = "src/aoc2015_05.rs"

[[bin]]
name = "aoc2015_06"
path = "src/aoc2015_06.rs"


[dependencies]
nom = "7.1.0"
itertools = "0.9.0"
md5 = "0.7.0"
