[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "aoc2015_01"
path = "src/aoc2015_01.rs"

[[bin]]
name = "aoc2015_02"
path = "src/aoc2015_02.rs"

[[bin]]
name = "aoc2015_03"
path = "src/aoc2015_03.rs"

[[bin]]
name = "aoc2015_04"
path = "src/aoc2015_04.rs"

[[bin]]
name = "aoc2015_05"
path = "src/aoc2015_05.rs"

[[bin]]
name = "aoc2015_06"
path = "src/aoc2015_06.rs"

[[bin]]
name = "aoc2015_07"
path = "src/aoc2015_07.rs"

[[bin]]
name = "aoc2015_08"
path = "src/aoc2015_08.rs"

[[bin]]
name = "aoc2015_09"
path = "src/aoc2015_09.rs"

[[bin]]
name = "aoc2015_10"
path = "src/aoc2015_10.rs"

[[bin]]
name = "aoc2015_11"
path = "src/aoc2015_11.rs"

[[bin]]
name = "aoc2015_12"
path = "src/aoc2015_12.rs"

[[bin]]
name = "aoc2015_13"
path = "src/aoc2015_13.rs"


[dependencies]
nom = "7.1.0"
itertools = "0.10.3"
md5 = "0.7.0"
json = "0.12.4"
